### ISSUE TITLE
DrupalGenerator dependency on chi-teck/drupal-code-generator:^2.0

### ISSUE THREAD

**Issue by xurizaemon** [kevinquillen/recipe-generator#4]
It looks like the use of DrupalGenerator in this depends on chi-teck/drupal-code-generator 2.x?

As of 3.0 (chi-teck/drupal-code-generator@175d7cf6aa13b693db024d838332adfd9d588bef) that class is removed.

Currently there is no explicit constraint for chi-teck/drupal-code-generator in this package.

If Drush 12 is installed, chi-teck/drupal-code-generator is already required at ^3.0. In such a project where chi-teck/drupal-code-generator was installed (at 3.3.x) before kevinquillen/recipe-generator,  `drush gen` did not see the recipe command for me.

- [`kevinquillen\Drush\Generators\RecipeGenerator`](https://github.com/kevinquillen/recipe-generator/blob/1.0.x/src/Drush/Generators/RecipeGenerator.php#L7) uses `DrupalCodeGenerator\Command\DrupalGenerator`
- [`DrupalCodeGenerator\Command\DrupalGenerator` in 2.x](https://github.com/Chi-teck/drupal-code-generator/blob/2.x/src/Command/DrupalGenerator.php)
- https://github.com/Chi-teck/drupal-code-generator/releases/tag/3.0.0

**Comment by xurizaemon** [comment]
I see that drush/drush[12.4.3, ..., 12.x-dev] require chi-teck/drupal-code-generator ^3.0 already. It probably doesn't make sense to do #5 at all then, the generator will need updating I expect.

**Comment by kevinquillen** [comment]
Believe this is resolved in the 2.0.x branch with Drush 13 as a dependency.
